---

- name: Include platform-specific variables
  include_vars: "vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}-{{ clang_version }}.yml"

- name: Add LLVM APT key
  apt_key:
    url: https://apt.llvm.org/llvm-snapshot.gpg.key
    state: present

- name: Add LLVM APT repository
  apt_repository:
    repo: "{{ llvm_apt_repo }}"
    state: present
    update_cache: yes

- name: Add APT key for libstdc++ (Ubuntu Trusty)
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: 1E9377A2BA9EF27F
    state: present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "trusty"

- name: Add APT repository for libstdc++ (Ubuntu Trusty)
  apt_repository:
    repo: deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "trusty"

- name: Install Clang
  apt:
    name: clang-{{ clang_version }}
    state: present

- name: Set clang as default C compiler
  copy:
    content: export CC=clang-{{ clang_version }}
    dest: /etc/profile.d/set-clang-cc.sh
  when: set_clang_cc

